language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm run build
after_success:
  - bash deploy.sh
env:
  global:
    - secure: RyqiSwAjvxoKidbU7xMSE0bQ0sDjXOB+2rXCGcrgU9aDhlLk4whNYOhsaVKvhNPRY4PIQJRQ1ycbcW9WvXq39JLrD+c0EBKVXEiS52yWNa3ZWZSbgtaPJ21yTjdchBHp3PgJZBuFdaSJPm4Y3JiPORnPl+SZlkMDAugUgVPGyHgXOIBoPsYbZDyJgZndGskmjmrZUp0qbUlZ1G9+BLh7X0eCDkwHYPU1rm47/1hQLfgX9ODfo5VxoWK85XdajsmZb1quJNm7zgZtHeY2QL1L6te19flZVPockHzqQQa6vRSqlRyb6wZbwjn4kSRQicqMK/2mlIHb6r1in2c7j+BGj1pEx+dRiqasKtZKwbbSb1MwmO9u7WB7WKvo6YJ4+IFBNZ8/ENTKpZjHL13dmahs6LVowly8q9S+tc9mb0nsP47cqTBPBCK42O8saxDjLPoHbBGR2Tf1cvZTVF+xyRXdgRbYafdByjzU4teNwqzUVRN5lmB63XAfAZd9CXWcvkvUalzgI8rRby5Lj9p5Tjkza6pskey+oHkBRDaFh3Dv3gDIBUQHgQYOpWZ5xLU9gtC4J+/YlBybFmoi/Vrv5KbD6U0qeJVZa+LdfsnG3SVerpqIgodE+ThTpUc5PmuazKE2O3HxGsL1C1ZmFzYGiBbiiyng/vtq6jUyPwqIPeVCVJQ=